#!/bin/bash
#PBS -N 150505a
#PBS -o $HOME/bayestack/bayestack/chains_$PBS_JOBNAME/output-$PBS_JOBID.log
#PBS -e $HOME/bayestack/bayestack/chains_$PBS_JOBNAME/output-$PBS_JOBID.err
#PBS -S /bin/bash
#PBS -l walltime=72:00:00
#PBS -l nodes=1:ppn=48
#PBS -l mem=4GB
#PBS -m bea
#PBS -M eliabmalefahlo@gmail.com

RUNPATH=$HOME/bayestack/bayestack 
cd $RUNPATH

date
pwd

mpiexec.osc -np $PBS_NP ./bayestack.py bayestack_settings.py
date

