#!/bin/bash
#PBS -N 150522a
#PBS -o $HOME/bayestack/chains_$PBS_JOBNAME/output-$PBS_JOBID.log
#PBS -e $HOME/bayestack/chains_$PBS_JOBNAME/output-$PBS_JOBID.err
#PBS -S /bin/bash
#PBS -l walltime=72:00:00
#PBS -l nodes=2:ppn=48
#PBS -l mem=4GB
#PBS -m bea
#PBS -M jtlz2@astro.columbia.edu

RUNPATH=$HOME/bayestack
cd $RUNPATH

date
pwd

mpiexec.osc -np $PBS_NP ./bayestack.py bayestack_settings.py
date

